# Generated by Django 3.0.7 on 2021-02-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0002_auto_20210209_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descriptions',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
