# Generated by Django 3.0.7 on 2021-02-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0005_auto_20210214_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
